name: build-php-extension
description: Build PHP Extension
author: php

branding:
  icon: package
  color: purple

inputs:
  extension-url:
    description: URL to the extension source code
    required: false
  extension-ref:
    description: Git reference in the extension repo
    required: false
  auth-token:
    description: Auth token to fetch the extension source code
    required: false
  php-version:
    description: PHP version to build
    required: true
  arch:
    description: Architecture to build
    required: true
  ts:
    description: Thread safety to build
    required: true
  args:
    description: Additional arguments to pass to the build script
    required: false
  libs:
    description: Libraries required to build the extension
    required: false
  run-tests:
    description: Run tests after building the extension
    required: false
    default: 'true'
  test-runner:
    description: Test runner to use
    required: false
    default: 'run-tests.php'
  build-directory:
    description: Directory to build the extension in
    required: false
    default: 'build'
  artifact-naming-scheme:
    description: Naming schema for the artifacts, pie or pecl
    deprecationMessage: "This will be removed once pie is released"
    required: false
    default: pie

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build PHP
      shell: pwsh
      env:
        CONFIGURE_ARGS: ${{inputs.args}}
        LIBRARIES: ${{inputs.libs}}
        ARTIFACT_NAMING_SCHEME: ${{inputs.artifact-naming-scheme}}
        RUN_TESTS: ${{inputs.run-tests}}
        TEST_RUNNER: ${{inputs.test-runner}}
        BUILD_DIRECTORY: ${{inputs.build-directory}}
        AUTH_TOKEN: ${{inputs.auth-token}}
      run: |
        Import-Module ${{ github.action_path }}\BuildPhpExtension -Force
        Invoke-PhpBuildExtension -ExtensionUrl "${{inputs.extension-url}}" `
                                 -ExtensionRef "${{inputs.extension-ref}}" `
                                 -PhpVersion ${{inputs.php-version}} `
                                 -Arch ${{inputs.arch}} `
                                 -Ts ${{inputs.ts}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{inputs.php-version}}-${{inputs.arch}}-${{inputs.ts}}
        path: artifacts/*
